const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const providers={
 silicon:{name:'硅基流动',endpoint:'https://api.siliconflow.cn/v1/chat/completions',models:['填写 Key 后点击 ↻']},
 lingke:{name:'灵客 AI',endpoint:'https://api.lingkeai.ai/v1/chat/completions',models:['填写 Key 后点击 ↻']},
 deepseek:{name:'DeepSeek',endpoint:'https://api.deepseek.com/chat/completions',models:['deepseek-chat','deepseek-reasoner']},
 openai:{name:'OpenAI',endpoint:'https://api.openai.com/v1/chat/completions',models:['gpt-5-mini','gpt-4.1-mini','gpt-image-1']},
 custom:{name:'自定义兼容 API',endpoint:'',models:['custom-model']}
};
const types=[['text','文本 / 剧本','生成剧本、提示词、分镜JSON'],['image','图片生成','人物、场景、分镜首帧'],['video','视频生成','文生视频或图生视频'],['check','一致性检查','人物、场景与道具质检'],['output','素材与成片','整理输出和下载']];
let state=JSON.parse(localStorage.getItem('cheng_v6')||'null')||{version:6,nodes:[],links:[],assets:[],selected:null,connecting:null,zoom:1,project:{name:'未命名视频项目',idea:'',episodes:1,duration:'3分钟'}};
const canvas=$('#canvas'),wires=$('#wires'),wrap=$('#canvasWrap');
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');setTimeout(()=>e.classList.remove('on'),1800)}
function save(){state.project={name:$('#projectName').value,idea:$('#idea').value,episodes:$('#episodes').value,duration:$('#duration').value};localStorage.setItem('cheng_v6',JSON.stringify(state));$('#status').textContent='V6 · 已保存'}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addNode(type){const meta=types.find(x=>x[0]===type)||types[0],id='n'+Date.now(),index=state.nodes.length;state.nodes.push({id,type,title:meta[1],x:70+(index%3)*240,y:90+Math.floor(index/3)*170,provider:'silicon',model:providers.silicon.models[0],endpoint:providers.silicon.endpoint,prompt:'',output:'',status:'等待'});state.selected=id;save();render();$('#nodeDialog').close()}
function render(){canvas.innerHTML='';state.nodes.forEach(n=>{const e=document.createElement('article');e.className='node'+(n.id===state.selected?' selected':'');e.dataset.id=n.id;e.style.left=n.x+'px';e.style.top=n.y+'px';e.innerHTML=`<div class="node-head"><span>${esc(n.title)}</span><i>${esc(n.status||'等待')}</i></div><div class="node-body"><div>${esc(types.find(x=>x[0]===n.type)?.[1]||n.type)}</div><div class="node-model">${esc(providers[n.provider]?.name||n.provider)} · ${esc(n.model)}</div><div class="ports"><button class="port in" title="输入端口">输入</button><button class="port out ${state.connecting===n.id?'pending':''}" title="输出端口">输出</button></div></div>`;e.onclick=()=>select(n.id);e.querySelector('.port.out').onclick=ev=>{ev.stopPropagation();state.connecting=n.id;$$('.port.out').forEach(p=>p.classList.remove('pending'));ev.currentTarget.classList.add('pending');toast('请选择另一个节点的输入端口')};e.querySelector('.port.in').onclick=ev=>{ev.stopPropagation();connect(n.id)};drag(e,n);canvas.appendChild(e)});draw();canvas.style.transform=`scale(${state.zoom})`;wires.style.transform=`scale(${state.zoom})`;$('#zoomText').textContent=Math.round(state.zoom*100)+'%';renderInspector();renderTasks()}
function select(id){state.selected=id;save();render()}
function connect(target){if(!state.connecting)return toast('请先点击起始节点的输出端口');if(state.connecting===target)return toast('不能连接到自身');state.links=state.links.filter(l=>l.to!==target);state.links.push({from:state.connecting,to:target});state.connecting=null;save();render();toast('节点已连接')}
function draw(){wires.innerHTML=state.links.map(l=>{const a=state.nodes.find(n=>n.id===l.from),b=state.nodes.find(n=>n.id===l.to);if(!a||!b)return'';const x1=a.x+190,y1=a.y+83,x2=b.x,y2=b.y+83,m=(x1+x2)/2;return `<path class="wire" d="M${x1} ${y1} C${m} ${y1},${m} ${y2},${x2} ${y2}"/>`}).join('')}
function drag(el,n){const h=el.querySelector('.node-head');h.onpointerdown=e=>{e.stopPropagation();const sx=e.clientX,sy=e.clientY,ox=n.x,oy=n.y;h.setPointerCapture(e.pointerId);h.onpointermove=m=>{n.x=Math.max(0,ox+(m.clientX-sx)/state.zoom);n.y=Math.max(55,oy+(m.clientY-sy)/state.zoom);el.style.left=n.x+'px';el.style.top=n.y+'px';draw()};h.onpointerup=()=>{h.onpointermove=null;save()}}}
function renderInspector(){const n=state.nodes.find(x=>x.id===state.selected);$('#emptyInspect').hidden=!!n;$('#nodeEditor').hidden=!n;if(!n)return;$('#nodeType').textContent=(types.find(x=>x[0]===n.type)?.[1]||n.type).toUpperCase();$('#nodeTitle').textContent=n.title;$('#nodeName').value=n.title;$('#provider').innerHTML=Object.entries(providers).map(([k,p])=>`<option value="${k}" ${k===n.provider?'selected':''}>${p.name}</option>`).join('');renderModels(n);$('#endpoint').value=n.endpoint||providers[n.provider]?.endpoint||'';$('#apiKey').value=sessionStorage.getItem('key_'+n.provider)||'';$('#prompt').value=n.prompt||'';$('#output').textContent=n.output||'尚未运行'}
function renderModels(n){const p=providers[$('#provider').value]||providers.custom;$('#model').innerHTML=p.models.map(m=>`<option ${m===n.model?'selected':''}>${esc(m)}</option>`).join('')}
function sync(){const n=state.nodes.find(x=>x.id===state.selected);if(!n)return;n.title=$('#nodeName').value;n.provider=$('#provider').value;n.model=$('#model').value;n.endpoint=$('#endpoint').value;n.prompt=$('#prompt').value;sessionStorage.setItem('key_'+n.provider,$('#apiKey').value);save();render()}
async function loadModels(){const n=state.nodes.find(x=>x.id===state.selected),key=$('#apiKey').value;if(!n||!key)return toast('请先填写 API Key');const bases={silicon:'https://api.siliconflow.cn/v1/models',lingke:'https://api.lingkeai.ai/v1/models'};const url=bases[n.provider];if(!url)return toast('该平台使用预设模型');try{const r=await fetch(url,{headers:{Authorization:'Bearer '+key}}),d=await r.json();if(!r.ok)throw Error(d.error?.message||d.message||'读取失败');const list=(d.data||[]).map(x=>x.id).filter(Boolean);if(!list.length)throw Error('没有返回模型');providers[n.provider].models=list;n.model=list[0];sessionStorage.setItem('key_'+n.provider,key);renderInspector();save();toast(`已加载 ${list.length} 个模型`)}catch(e){toast('读取失败：'+e.message)}}
async function runNode(n){if(!n)return;const key=sessionStorage.getItem('key_'+n.provider);if(!key)return toast('请填写 API Key');n.status='运行中';render();try{const input=state.links.filter(l=>l.to===n.id).map(l=>state.nodes.find(x=>x.id===l.from)?.output).filter(Boolean).join('\n')||state.project.idea;const r=await fetch(n.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({model:n.model,messages:[{role:'system',content:n.prompt||'按用户要求完成任务'},{role:'user',content:input||'请开始'}]})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||d.message||'调用失败');n.output=d.choices?.[0]?.message?.content||JSON.stringify(d,null,2);n.status='完成'}catch(e){n.output='错误：'+e.message;n.status='失败'}save();render()}
function renderTasks(){$('#taskList').innerHTML=state.nodes.map(n=>`<div class="task"><span>${esc(n.title)}</span><i>${esc(n.status)}</i></div>`).join('')||'<small>暂无任务</small>'}
function showTab(name){['project','assets','tasks'].forEach(x=>$('#'+x+'Panel').hidden=x!==name);$$('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===name))}
function renderAssets(){$('#assetList').innerHTML=state.assets.map(a=>`<div class="asset"><img src="${a.image}"><span>${esc(a.name)}</span></div>`).join('')||'<small>暂无角色参考图</small>'}
$('#nodeCatalog').innerHTML=types.map(t=>`<button class="catalog" data-type="${t[0]}"><strong>${t[1]}</strong><small>${t[2]}</small></button>`).join('');$$('.catalog').forEach(b=>b.onclick=()=>addNode(b.dataset.type));$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('#addNode').onclick=()=>$('#nodeDialog').showModal();$('#deleteNode').onclick=()=>{if(!state.selected)return;state.nodes=state.nodes.filter(n=>n.id!==state.selected);state.links=state.links.filter(l=>l.from!==state.selected&&l.to!==state.selected);state.selected=null;save();render()};$('#clearCanvas').onclick=()=>{if(confirm('确定清空全部节点和连线？')){state.nodes=[];state.links=[];state.selected=null;save();render()}};
$('#provider').onchange=()=>{const n=state.nodes.find(x=>x.id===state.selected);n.provider=$('#provider').value;n.endpoint=providers[n.provider].endpoint;n.model=providers[n.provider].models[0];renderInspector();save()};['nodeName','model','endpoint','apiKey','prompt'].forEach(id=>$('#'+id).onchange=sync);$('#loadModels').onclick=loadModels;$('#testApi').onclick=loadModels;$('#runNode').onclick=()=>runNode(state.nodes.find(x=>x.id===state.selected));$('#runAll').onclick=async()=>{for(const n of state.nodes)await runNode(n)};
$('#zoomIn').onclick=()=>{state.zoom=Math.min(1.4,state.zoom+.1);render()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(.5,state.zoom-.1);render()};wrap.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.5,Math.min(1.4,state.zoom+(e.deltaY<0?.08:-.08)));render();save()};
let pan;wrap.onpointerdown=e=>{if(e.target!==wrap)return;pan={x:e.clientX,y:e.clientY,l:wrap.scrollLeft,t:wrap.scrollTop};wrap.setPointerCapture(e.pointerId)};wrap.onpointermove=e=>{if(pan){wrap.scrollLeft=pan.l-(e.clientX-pan.x);wrap.scrollTop=pan.t-(e.clientY-pan.y)}};wrap.onpointerup=()=>pan=null;
['projectName','idea','episodes','duration'].forEach(id=>$('#'+id).oninput=save);$('#settings').onclick=()=>{renderApiList();$('#apiDialog').showModal()};function renderApiList(){$('#apiList').innerHTML=Object.entries(providers).map(([k,p])=>`<label class="api-row"><span>${p.name}</span><input type="password" data-key="${k}" value="${esc(sessionStorage.getItem('key_'+k)||'')}" placeholder="API Key"></label>`).join('');$$('[data-key]').forEach(e=>e.onchange=()=>sessionStorage.setItem('key_'+e.dataset.key,e.value))}
$('#addAsset').onclick=()=>$('#assetFile').click();$('#assetFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{state.assets.push({id:Date.now(),name:f.name,image:r.result});save();renderAssets()};r.readAsDataURL(f)};
$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='成成的工作台项目.json';a.click()};$('#import').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=async e=>{try{state=JSON.parse(await e.target.files[0].text());save();render();renderAssets()}catch{toast('项目文件无效')}};
$('#projectName').value=state.project.name;$('#idea').value=state.project.idea;$('#episodes').value=state.project.episodes;$('#duration').value=state.project.duration;render();renderAssets();showTab('project');
