const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const providers={
 silicon:{name:'硅基流动',endpoint:'https://api.siliconflow.cn/v1/chat/completions',models:['填写 Key 后点击 ↻']},
 lingke:{name:'灵客 AI',endpoint:'https://api.lingkeai.ai/v1/chat/completions',models:['填写 Key 后点击 ↻']},
 deepseek:{name:'DeepSeek',endpoint:'https://api.deepseek.com/chat/completions',models:['deepseek-chat','deepseek-reasoner']},
 openai:{name:'OpenAI',endpoint:'https://api.openai.com/v1/chat/completions',models:['gpt-5-mini','gpt-4.1-mini','gpt-image-1']},
 custom:{name:'自定义兼容 API',endpoint:'',models:['custom-model']}
};
const types=[['txt','TXT 文本','本地输入想法、剧本或任意文字'],['text','AI 文本 / 剧本','调用大模型生成剧本、提示词、分镜JSON'],['image','图片生成','人物、场景、分镜首帧'],['video','视频生成','文生视频或图生视频'],['check','一致性检查','人物、场景与道具质检'],['output','素材与成片','整理输出和下载']];
let state=JSON.parse(localStorage.getItem('cheng_v6')||'null')||{version:6,nodes:[],links:[],assets:[],selected:null,connecting:null,zoom:1,project:{name:'未命名视频项目',idea:'',episodes:1,duration:'3分钟',type:'短剧',ratio:'16:9 横屏',visualStyle:''}};
const canvas=$('#canvas'),wires=$('#wires'),wrap=$('#canvasWrap');
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');setTimeout(()=>e.classList.remove('on'),1800)}
function save(){state.project={name:$('#projectName').value,idea:$('#idea').value,episodes:$('#episodes').value,duration:$('#duration').value,type:$('#projectType').value,ratio:$('#ratio').value,visualStyle:$('#visualStyle').value};localStorage.setItem('cheng_v6',JSON.stringify(state));$('#status').textContent='V6 · 已保存'}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addNode(type){const meta=types.find(x=>x[0]===type)||types[0],id='n'+Date.now(),index=state.nodes.length,drop=state.pendingDrop,isTxt=type==='txt';state.nodes.push({id,type,title:meta[1],x:drop?.x??70+(index%3)*240,y:drop?.y??90+Math.floor(index/3)*170,provider:isTxt?'custom':'silicon',model:isTxt?'本地文本':providers.silicon.models[0],endpoint:isTxt?'':providers.silicon.endpoint,prompt:'',output:'',status:'等待'});if(drop?.from){if(drop.direction==='input')state.links.push({from:id,to:drop.from});else state.links.push({from:drop.from,to:id})}state.pendingDrop=null;state.connecting=null;state.selected=id;save();render();$('#nodeDialog').close()}
function render(){canvas.innerHTML='';state.nodes.forEach(n=>{const e=document.createElement('article');e.className='node'+(n.id===state.selected?' selected':'');e.dataset.id=n.id;e.dataset.type=n.type;e.style.left=n.x+'px';e.style.top=n.y+'px';const model=n.type==='txt'?'本地文本 · 无需 API':`${providers[n.provider]?.name||n.provider} · ${n.model}`,inline=n.type==='txt'?`<textarea class="node-text" placeholder="直接在节点里输入文字……">${esc(n.prompt||'')}</textarea>`:'';e.innerHTML=`<div class="node-head"><span>${esc(n.title)}</span><i>${esc(n.status||'等待')}</i></div><div class="node-body">${inline||`<div>${esc(types.find(x=>x[0]===n.type)?.[1]||n.type)}</div><div class="node-model">${esc(model)}</div>`}<div class="ports"><button class="port in" title="输入端口：可向前拖出上游节点"></button><button class="port out" title="输出端口：向后拖出下游节点"></button></div></div>`;e.onclick=()=>select(n.id);const text=e.querySelector('.node-text');if(text){['pointerdown','click','dblclick','keydown','keyup'].forEach(type=>text.addEventListener(type,ev=>ev.stopPropagation()));text.onfocus=()=>{state.selected=n.id;e.classList.add('selected')};text.oninput=()=>{n.prompt=text.value;n.output=text.value;n.status=text.value?'就绪':'等待';e.querySelector('.node-head i').textContent=n.status;save()}}e.querySelector('.port.out').onpointerdown=ev=>startConnection(ev,n,'output');e.querySelector('.port.in').onpointerdown=ev=>startConnection(ev,n,'input');drag(e,n);canvas.appendChild(e)});draw();canvas.style.transform=`scale(${state.zoom})`;wires.style.transform=`scale(${state.zoom})`;$('#zoomText').textContent=Math.round(state.zoom*100)+'%';renderInspector();renderTasks()}
function select(id){state.selected=id;save();render()}
function connect(target){if(!state.connecting)return toast('请先点击起始节点的输出端口');if(state.connecting===target)return toast('不能连接到自身');state.links=state.links.filter(l=>l.to!==target);state.links.push({from:state.connecting,to:target});state.connecting=null;save();render();toast('节点已连接')}
function startConnection(ev,node,direction){ev.preventDefault();ev.stopPropagation();state.connecting=node.id;const el=canvas.querySelector(`.node[data-id="${node.id}"]`),start={x:node.x+(direction==='output'?el.offsetWidth:0),y:node.y+el.offsetHeight/2},path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('class','wire active');wires.appendChild(path);ev.currentTarget.classList.add('pending');const point=e=>{const r=wrap.getBoundingClientRect();return{x:(e.clientX-r.left+wrap.scrollLeft)/state.zoom,y:(e.clientY-r.top+wrap.scrollTop)/state.zoom}};const move=e=>{const p=point(e),m=(start.x+p.x)/2;path.setAttribute('d',`M${start.x} ${start.y} C${m} ${start.y},${m} ${p.y},${p.x} ${p.y}`)};const up=e=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);const wanted=direction==='output'?'.port.in':'.port.out',hit=document.elementFromPoint(e.clientX,e.clientY)?.closest(wanted),target=hit?.closest('.node')?.dataset.id;if(target&&target!==node.id){if(direction==='output')connect(target);else{state.links=state.links.filter(l=>l.to!==node.id);state.links.push({from:target,to:node.id});state.connecting=null;save();render();toast('节点已连接')}return}const p=point(e);state.pendingDrop={from:node.id,direction,x:Math.max(10,p.x-(direction==='input'?170:20)),y:Math.max(55,p.y-45)};$('#nodeDialogTitle').textContent=direction==='input'?'添加并连接上游节点':'添加并连接下一个节点';$('#nodeDialogHint').textContent='选择节点类型后，将在松开位置创建并自动连线';$('#nodeDialog').showModal();draw()};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)}
function draw(){wires.innerHTML=state.links.map(l=>{const a=state.nodes.find(n=>n.id===l.from),b=state.nodes.find(n=>n.id===l.to),ae=a&&canvas.querySelector(`.node[data-id="${a.id}"]`),be=b&&canvas.querySelector(`.node[data-id="${b.id}"]`);if(!a||!b||!ae||!be)return'';const x1=a.x+ae.offsetWidth,y1=a.y+ae.offsetHeight/2,x2=b.x,y2=b.y+be.offsetHeight/2,m=(x1+x2)/2;return `<path class="wire" d="M${x1} ${y1} C${m} ${y1},${m} ${y2},${x2} ${y2}"/>`}).join('')}
function drag(el,n){const h=el.querySelector('.node-head');h.onpointerdown=e=>{e.stopPropagation();const sx=e.clientX,sy=e.clientY,ox=n.x,oy=n.y;h.setPointerCapture(e.pointerId);h.onpointermove=m=>{n.x=Math.max(0,ox+(m.clientX-sx)/state.zoom);n.y=Math.max(55,oy+(m.clientY-sy)/state.zoom);el.style.left=n.x+'px';el.style.top=n.y+'px';draw()};h.onpointerup=()=>{h.onpointermove=null;save()}}}
function renderInspector(){const n=state.nodes.find(x=>x.id===state.selected);$('#emptyInspect').hidden=!!n;$('#nodeEditor').hidden=!n;if(!n)return;const isTxt=n.type==='txt';$('#nodeType').textContent=(types.find(x=>x[0]===n.type)?.[1]||n.type).toUpperCase();$('#nodeTitle').textContent=n.title;$('#nodeName').value=n.title;$('#aiSettings').hidden=isTxt;$('#testApi').hidden=isTxt;$('#promptLabel').textContent=isTxt?'TXT 文本内容':'AI 工作要求（系统提示词）';$('#promptHelp').textContent=isTxt?'这里写的文字会原样传给下一个节点。':'告诉 AI 扮演什么角色、完成什么任务、按什么格式输出。';$('#prompt').placeholder=isTxt?'在这里输入想法、剧本、提示词或任意文本……':'例如：你是专业编剧，根据输入生成三幕式剧本，只输出 JSON。';$('#provider').innerHTML=Object.entries(providers).map(([k,p])=>`<option value="${k}" ${k===n.provider?'selected':''}>${p.name}</option>`).join('');renderModels(n);$('#endpoint').value=n.endpoint||providers[n.provider]?.endpoint||'';$('#apiKey').value=sessionStorage.getItem('key_'+n.provider)||'';$('#prompt').value=n.prompt||'';$('#output').textContent=n.output||'尚未运行'}
function renderModels(n){const p=providers[$('#provider').value]||providers.custom;$('#model').innerHTML=p.models.map(m=>`<option ${m===n.model?'selected':''}>${esc(m)}</option>`).join('')}
function sync(){const n=state.nodes.find(x=>x.id===state.selected);if(!n)return;n.title=$('#nodeName').value;n.provider=$('#provider').value;n.model=$('#model').value;n.endpoint=$('#endpoint').value;n.prompt=$('#prompt').value;sessionStorage.setItem('key_'+n.provider,$('#apiKey').value);save();render()}
async function loadModels(){const n=state.nodes.find(x=>x.id===state.selected),key=$('#apiKey').value;if(!n||!key){$('#output').textContent='请先填写 API Key，再点击读取模型。';return toast('请先填写 API Key')}const bases={silicon:'https://api.siliconflow.cn/v1/models',lingke:'https://api.lingkeai.ai/v1/models'};const url=bases[n.provider];if(!url)return toast('该平台使用预设模型');$('#output').textContent='正在连接 '+providers[n.provider].name+' 并读取模型列表…';try{const r=await fetch(url,{headers:{Authorization:'Bearer '+key}}),text=await r.text();let d;try{d=JSON.parse(text)}catch{d={message:text}}if(!r.ok)throw Error(d.error?.message||d.message||`HTTP ${r.status}`);const list=(Array.isArray(d)?d:d.data||[]).map(x=>typeof x==='string'?x:x.id).filter(Boolean);if(!list.length)throw Error('接口成功，但没有返回可用模型');providers[n.provider].models=list;n.model=list[0];sessionStorage.setItem('key_'+n.provider,key);renderInspector();$('#output').textContent=`连接成功：已加载 ${list.length} 个模型。`;save();toast(`已加载 ${list.length} 个模型`)}catch(e){n.output='模型读取失败：'+e.message;$('#output').textContent=n.output;toast(n.output)}}
async function runNode(n){if(!n)return;if(n.type==='txt'){n.output=n.prompt;n.status='完成';save();render();return toast('TXT 文本已传递')}const key=sessionStorage.getItem('key_'+n.provider);if(!key)return toast('请填写 API Key');n.status='运行中';render();try{const input=state.links.filter(l=>l.to===n.id).map(l=>state.nodes.find(x=>x.id===l.from)?.output).filter(Boolean).join('\n')||state.project.idea;const r=await fetch(n.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({model:n.model,messages:[{role:'system',content:n.prompt||'按用户要求完成任务'},{role:'user',content:input||'请开始'}]})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||d.message||'调用失败');n.output=d.choices?.[0]?.message?.content||JSON.stringify(d,null,2);n.status='完成'}catch(e){n.output='错误：'+e.message;n.status='失败'}save();render()}
function renderTasks(){$('#taskList').innerHTML=state.nodes.map(n=>`<div class="task"><span>${esc(n.title)}</span><i>${esc(n.status)}</i></div>`).join('')||'<small>暂无任务</small>'}
function showTab(name){['project','assets','tasks'].forEach(x=>$('#'+x+'Panel').hidden=x!==name);$$('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===name))}
function renderAssets(){$('#assetList').innerHTML=state.assets.map(a=>`<div class="asset"><img src="${a.image}"><span>${esc(a.name)}</span></div>`).join('')||'<small>暂无角色参考图</small>'}
$('#nodeCatalog').innerHTML=types.map(t=>`<button class="catalog" data-type="${t[0]}"><strong>${t[1]}</strong><small>${t[2]}</small></button>`).join('');$$('.catalog').forEach(b=>b.onclick=()=>addNode(b.dataset.type));$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('#addNode').onclick=()=>{state.pendingDrop=null;$('#nodeDialogTitle').textContent='添加节点';$('#nodeDialogHint').textContent='选择要添加的节点类型';$('#nodeDialog').showModal()};$('#cancelNode').onclick=()=>{state.pendingDrop=null;state.connecting=null;draw();$('#nodeDialog').close()};$('#deleteNode').onclick=()=>{if(!state.selected)return;state.nodes=state.nodes.filter(n=>n.id!==state.selected);state.links=state.links.filter(l=>l.from!==state.selected&&l.to!==state.selected);state.selected=null;save();render()};$('#clearCanvas').onclick=()=>{if(confirm('确定清空全部节点和连线？')){state.nodes=[];state.links=[];state.selected=null;save();render()}};
$('#provider').onchange=()=>{const n=state.nodes.find(x=>x.id===state.selected);n.provider=$('#provider').value;n.endpoint=providers[n.provider].endpoint;n.model=providers[n.provider].models[0];renderInspector();save()};['nodeName','model','endpoint','apiKey','prompt'].forEach(id=>$('#'+id).onchange=sync);$('#prompt').oninput=()=>{const n=state.nodes.find(x=>x.id===state.selected);if(n){n.prompt=$('#prompt').value;save()}};$('#apiKey').oninput=()=>{const n=state.nodes.find(x=>x.id===state.selected);if(n)sessionStorage.setItem('key_'+n.provider,$('#apiKey').value)};$('#loadModels').onclick=loadModels;$('#testApi').onclick=loadModels;$('#runNode').onclick=()=>runNode(state.nodes.find(x=>x.id===state.selected));$('#runAll').onclick=async()=>{for(const n of state.nodes)await runNode(n)};
$('#zoomIn').onclick=()=>{state.zoom=Math.min(1.4,state.zoom+.1);render()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(.5,state.zoom-.1);render()};wrap.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.5,Math.min(1.4,state.zoom+(e.deltaY<0?.08:-.08)));render();save()};
let pan;wrap.onpointerdown=e=>{if(e.target.closest?.('.node')||e.target.closest?.('.toolbar'))return;pan={x:e.clientX,y:e.clientY,l:wrap.scrollLeft,t:wrap.scrollTop};wrap.setPointerCapture(e.pointerId)};wrap.onpointermove=e=>{if(pan){wrap.scrollLeft=pan.l-(e.clientX-pan.x);wrap.scrollTop=pan.t-(e.clientY-pan.y)}};wrap.onpointerup=()=>pan=null;wrap.ondblclick=e=>{if(e.target.closest?.('.node'))return;const r=wrap.getBoundingClientRect();state.pendingDrop={x:(e.clientX-r.left+wrap.scrollLeft)/state.zoom-30,y:(e.clientY-r.top+wrap.scrollTop)/state.zoom-35};$('#nodeDialogTitle').textContent='在这里添加节点';$('#nodeDialogHint').textContent='选择节点类型后，将在双击位置创建';$('#nodeDialog').showModal()};
['projectName','idea','episodes','duration','projectType','ratio','visualStyle'].forEach(id=>$('#'+id).oninput=save);$('#settings').onclick=()=>{renderApiList();$('#apiDialog').showModal()};function renderApiList(){$('#apiList').innerHTML=Object.entries(providers).map(([k,p])=>`<label class="api-row"><span>${p.name}</span><input type="password" data-key="${k}" value="${esc(sessionStorage.getItem('key_'+k)||'')}" placeholder="API Key"></label>`).join('');$$('[data-key]').forEach(e=>e.onchange=()=>sessionStorage.setItem('key_'+e.dataset.key,e.value))}
$('#addAsset').onclick=()=>$('#assetFile').click();$('#assetFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{state.assets.push({id:Date.now(),name:f.name,image:r.result});save();renderAssets()};r.readAsDataURL(f)};
$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='成成的工作台项目.json';a.click()};$('#import').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=async e=>{try{state=JSON.parse(await e.target.files[0].text());save();render();renderAssets()}catch{toast('项目文件无效')}};
$('#projectName').value=state.project.name;$('#idea').value=state.project.idea;$('#episodes').value=state.project.episodes;$('#duration').value=state.project.duration;$('#projectType').value=state.project.type||'短剧';$('#ratio').value=state.project.ratio||'16:9 横屏';$('#visualStyle').value=state.project.visualStyle||'';render();renderAssets();showTab('project');
