const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const providers={
 silicon:{name:'硅基流动',endpoint:'https://api.siliconflow.cn/v1/chat/completions',models:['填写 Key 后点击 ↻']},
 lingke:{name:'灵客 AI',endpoint:'https://api.lingkeai.ai/v1/chat/completions',models:['填写 Key 后点击 ↻']},
 deepseek:{name:'DeepSeek',endpoint:'https://api.deepseek.com/chat/completions',models:['deepseek-chat','deepseek-reasoner']},
 openai:{name:'OpenAI',endpoint:'https://api.openai.com/v1/chat/completions',models:['gpt-5-mini','gpt-4.1-mini','gpt-image-1']},
 custom:{name:'自定义兼容 API',endpoint:'',models:['custom-model']}
};
Object.keys(providers).forEach(key=>{try{const cached=JSON.parse(sessionStorage.getItem('models_'+key)||'null');if(Array.isArray(cached)&&cached.length)providers[key].models=cached}catch{}});
const types=[['txt','TXT 文本','本地输入想法、剧本或任意文字'],['text','AI 文本 / 剧本','调用大模型生成剧本、提示词、分镜JSON'],['image','图片生成','人物、场景、分镜首帧'],['video','视频生成','文生视频或图生视频'],['check','一致性检查','人物、场景与道具质检'],['output','素材与成片','整理输出和下载']];
let state=JSON.parse(localStorage.getItem('cheng_v6')||'null')||{version:6,nodes:[],links:[],assets:[],selected:null,connecting:null,zoom:1,project:{name:'未命名视频项目',idea:'',episodes:1,duration:'3分钟',type:'短剧',ratio:'16:9 横屏',visualStyle:''}};
state.nodes.forEach((n,i)=>{if(!n.seq)n.seq=i+1});
const canvas=$('#canvas'),wires=$('#wires'),wrap=$('#canvasWrap');
const apiEndpoint=n=>n?.type==='image'&&n?.provider==='silicon'?'https://api.siliconflow.cn/v1/images/generations':providers[n?.provider]?.endpoint||n?.endpoint||'';
const seqText=n=>String(n.seq||state.nodes.indexOf(n)+1).padStart(2,'0');
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');setTimeout(()=>e.classList.remove('on'),1800)}
function save(){state.project={name:$('#projectName').value,idea:$('#idea').value,episodes:$('#episodes').value,duration:$('#duration').value,type:$('#projectType').value,ratio:$('#ratio').value,visualStyle:$('#visualStyle').value};localStorage.setItem('cheng_v6',JSON.stringify(state));$('#status').textContent='V6 · 已保存'}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addNode(type){const meta=types.find(x=>x[0]===type)||types[0],id='n'+Date.now(),index=state.nodes.length,drop=state.pendingDrop,isTxt=type==='txt',isImage=type==='image',seq=Math.max(0,...state.nodes.map(n=>n.seq||0))+1;state.nodes.push({id,type,seq,title:meta[1],x:drop?.x??70+(index%3)*240,y:drop?.y??90+Math.floor(index/3)*170,provider:isTxt?'custom':'silicon',model:isTxt?'本地文本':isImage?'Kwai-Kolors/Kolors':providers.silicon.models[0],endpoint:isTxt?'':isImage?'https://api.siliconflow.cn/v1/images/generations':providers.silicon.endpoint,prompt:'',negativePrompt:'',imageSize:'1024x1024',output:'',status:'等待'});if(drop?.from){if(drop.direction==='input')state.links.push({from:id,to:drop.from});else state.links.push({from:drop.from,to:id})}state.pendingDrop=null;state.connecting=null;state.selected=id;save();render();$('#nodeDialog').close()}
function render(){canvas.innerHTML='';state.nodes.forEach(n=>{const e=document.createElement('article');e.className='node'+(n.id===state.selected?' selected':'');e.dataset.id=n.id;e.dataset.type=n.type;e.style.left=n.x+'px';e.style.top=n.y+'px';const model=n.type==='txt'?'本地文本 · 无需 API':`${providers[n.provider]?.name||n.provider} · ${n.model}`,inline=n.type==='txt'?`<textarea class="node-text" placeholder="直接在节点里输入文字……">${esc(n.prompt||'')}</textarea>`:'',thumb=n.type==='image'&&n.output?.startsWith('http')?`<img class="node-thumb" src="${esc(n.output)}" alt="生成图片">`:'';e.innerHTML=`<div class="node-head"><b class="seq">${seqText(n)}</b><span>${esc(n.title)}</span><i>${esc(n.status||'等待')}</i></div><div class="node-body">${inline||`<div>${esc(types.find(x=>x[0]===n.type)?.[1]||n.type)}</div><div class="node-model">${esc(model)}</div>${thumb}`}<div class="ports"><button class="port in" title="输入端口：可向前拖出上游节点"></button><button class="port out" title="输出端口：向后拖出下游节点"></button></div></div>`;e.onclick=()=>select(n.id);const text=e.querySelector('.node-text');if(text){['pointerdown','click','dblclick','keydown','keyup'].forEach(type=>text.addEventListener(type,ev=>ev.stopPropagation()));text.onfocus=()=>{state.selected=n.id;$$('.node').forEach(x=>x.classList.remove('selected'));e.classList.add('selected');renderInspector();save()};text.oninput=()=>{n.prompt=text.value;n.output=text.value;n.status=text.value?'就绪':'等待';e.querySelector('.node-head i').textContent=n.status;save()}}e.querySelector('.port.out').onpointerdown=ev=>startConnection(ev,n,'output');e.querySelector('.port.in').onpointerdown=ev=>startConnection(ev,n,'input');drag(e,n);canvas.appendChild(e)});draw();canvas.style.transform=`scale(${state.zoom})`;wires.style.transform=`scale(${state.zoom})`;$('#zoomText').textContent=Math.round(state.zoom*100)+'%';renderInspector();renderTasks();renderFlow()}
function renderFlow(){const byId=Object.fromEntries(state.nodes.map(n=>[n.id,n])),incoming=new Set(state.links.map(l=>l.to)),ordered=[],seen=new Set(),walk=n=>{if(!n||seen.has(n.id))return;seen.add(n.id);ordered.push(n);state.links.filter(l=>l.from===n.id).forEach(l=>walk(byId[l.to]))};state.nodes.filter(n=>!incoming.has(n.id)).sort((a,b)=>a.seq-b.seq).forEach(walk);state.nodes.sort((a,b)=>a.seq-b.seq).forEach(walk);$('#flowMap').innerHTML=ordered.map((n,i)=>`${i?'<span class="flow-arrow">→</span>':''}<button class="flow-step" data-flow="${n.id}"><b>${seqText(n)}</b>${esc(n.title)}</button>`).join('');$$('[data-flow]').forEach(b=>b.onclick=()=>{select(b.dataset.flow);const n=byId[b.dataset.flow];wrap.scrollTo({left:Math.max(0,n.x-80),top:Math.max(0,n.y-120),behavior:'smooth'})})}
function select(id){state.selected=id;save();render()}
function connect(target){if(!state.connecting)return toast('请先点击起始节点的输出端口');if(state.connecting===target)return toast('不能连接到自身');state.links=state.links.filter(l=>l.to!==target);state.links.push({from:state.connecting,to:target});state.connecting=null;save();render();toast('节点已连接')}
function startConnection(ev,node,direction){ev.preventDefault();ev.stopPropagation();state.connecting=node.id;const el=canvas.querySelector(`.node[data-id="${node.id}"]`),start={x:node.x+(direction==='output'?el.offsetWidth:0),y:node.y+el.offsetHeight/2},path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('class','wire active');wires.appendChild(path);ev.currentTarget.classList.add('pending');const point=e=>{const r=wrap.getBoundingClientRect();return{x:(e.clientX-r.left+wrap.scrollLeft)/state.zoom,y:(e.clientY-r.top+wrap.scrollTop)/state.zoom}};const move=e=>{const p=point(e),m=(start.x+p.x)/2;path.setAttribute('d',`M${start.x} ${start.y} C${m} ${start.y},${m} ${p.y},${p.x} ${p.y}`)};const up=e=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);const wanted=direction==='output'?'.port.in':'.port.out',hit=document.elementFromPoint(e.clientX,e.clientY)?.closest(wanted),target=hit?.closest('.node')?.dataset.id;if(target&&target!==node.id){if(direction==='output')connect(target);else{state.links=state.links.filter(l=>l.to!==node.id);state.links.push({from:target,to:node.id});state.connecting=null;save();render();toast('节点已连接')}return}const p=point(e);state.pendingDrop={from:node.id,direction,x:Math.max(10,p.x-(direction==='input'?170:20)),y:Math.max(55,p.y-45)};$('#nodeDialogTitle').textContent=direction==='input'?'添加并连接上游节点':'添加并连接下一个节点';$('#nodeDialogHint').textContent='选择节点类型后，将在松开位置创建并自动连线';$('#nodeDialog').showModal();draw()};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)}
function draw(){wires.innerHTML=state.links.map(l=>{const a=state.nodes.find(n=>n.id===l.from),b=state.nodes.find(n=>n.id===l.to),ae=a&&canvas.querySelector(`.node[data-id="${a.id}"]`),be=b&&canvas.querySelector(`.node[data-id="${b.id}"]`);if(!a||!b||!ae||!be)return'';const x1=a.x+ae.offsetWidth,y1=a.y+ae.offsetHeight/2,x2=b.x,y2=b.y+be.offsetHeight/2,m=(x1+x2)/2;return `<path class="wire" d="M${x1} ${y1} C${m} ${y1},${m} ${y2},${x2} ${y2}"/>`}).join('')}
function drag(el,n){const h=el.querySelector('.node-head');h.onpointerdown=e=>{e.stopPropagation();const sx=e.clientX,sy=e.clientY,ox=n.x,oy=n.y;h.setPointerCapture(e.pointerId);h.onpointermove=m=>{n.x=Math.max(0,ox+(m.clientX-sx)/state.zoom);n.y=Math.max(55,oy+(m.clientY-sy)/state.zoom);el.style.left=n.x+'px';el.style.top=n.y+'px';draw()};h.onpointerup=()=>{h.onpointermove=null;save()}}}
function renderInspector(){const n=state.nodes.find(x=>x.id===state.selected);$('#emptyInspect').hidden=!!n;$('#nodeEditor').hidden=!n;if(!n)return;const isTxt=n.type==='txt',isImage=n.type==='image';$('#nodeType').textContent=`${seqText(n)} · ${(types.find(x=>x[0]===n.type)?.[1]||n.type).toUpperCase()}`;$('#nodeTitle').textContent=n.title;$('#nodeName').value=n.title;$('#aiSettings').hidden=isTxt;$('#imageSettings').hidden=!isImage;$('#testApi').hidden=isTxt;$('#promptLabel').textContent=isTxt?'TXT 文本内容':isImage?'图片提示词（不填写则使用上游节点或核心创意）':'AI 工作要求（系统提示词）';$('#promptHelp').textContent=isTxt?'这里写的文字会原样传给下一个节点。':isImage?'可直接写画面，也可留空，让图片节点自动读取前一个节点或左侧“核心创意”。':'告诉 AI 扮演什么角色、完成什么任务、按什么格式输出。';$('#prompt').placeholder=isTxt?'在这里输入想法、剧本、提示词或任意文本……':isImage?'例如：写实电影感，雨夜古墓入口，探险者手持矿灯，低饱和冷色':'例如：你是专业编剧，根据输入生成三幕式剧本，只输出 JSON。';$('#provider').innerHTML=Object.entries(providers).map(([k,p])=>`<option value="${k}" ${k===n.provider?'selected':''}>${p.name}</option>`).join('');renderModels(n);$('#endpoint').value=n.endpoint||apiEndpoint(n);$('#apiKey').value=sessionStorage.getItem('key_'+n.provider)||'';$('#prompt').value=n.prompt||'';$('#imageSize').value=n.imageSize||'1024x1024';$('#negativePrompt').value=n.negativePrompt||'';const imageUrl=isImage&&n.output?.startsWith('http')?n.output:'';$('#imagePreview').hidden=!imageUrl;$('#imagePreview').innerHTML=imageUrl?`<img src="${esc(imageUrl)}" alt="生成结果"><a href="${esc(imageUrl)}" target="_blank" rel="noopener">打开原图（平台链接约 1 小时有效）</a>`:'';$('#output').classList.toggle('error-box',n.status==='失败');$('#output').textContent=n.output||'尚未运行'}
function renderModels(n){const p=providers[$('#provider').value]||providers.custom,list=n.models?.length?[...n.models]:[...p.models];if(n.model&&!list.includes(n.model))list.unshift(n.model);$('#model').innerHTML=list.map(m=>`<option ${m===n.model?'selected':''}>${esc(m)}</option>`).join('')}
function sync(){const n=state.nodes.find(x=>x.id===state.selected);if(!n)return;n.title=$('#nodeName').value;n.provider=$('#provider').value;n.model=$('#model').value;n.endpoint=$('#endpoint').value;n.prompt=$('#prompt').value;n.imageSize=$('#imageSize').value;n.negativePrompt=$('#negativePrompt').value;sessionStorage.setItem('key_'+n.provider,$('#apiKey').value);save();render()}
async function loadModels(){const n=state.nodes.find(x=>x.id===state.selected),key=$('#apiKey').value;if(!n||!key){$('#output').textContent='请先填写 API Key，再点击读取模型。';return toast('请先填写 API Key')}const bases={silicon:'https://api.siliconflow.cn/v1/models',lingke:'https://api.lingkeai.ai/v1/models'};const url=bases[n.provider];if(!url)return toast('该平台使用预设模型');$('#output').textContent='正在连接 '+providers[n.provider].name+' 并读取模型列表…';try{const r=await fetch(url,{headers:{Authorization:'Bearer '+key}}),text=await r.text();let d;try{d=JSON.parse(text)}catch{d={message:text}}if(!r.ok)throw Error(d.error?.message||d.message||`HTTP ${r.status}`);const raw=Array.isArray(d)?d:d.data||[],all=raw.map(x=>typeof x==='string'?{id:x}:x).filter(x=>x.id),imagePattern=/(Kolors|FLUX|stable-diffusion|Qwen-Image|HiDream|image)/i;let list=(n.type==='image'?all.filter(x=>x.type==='image'||imagePattern.test(x.id)):all.filter(x=>x.type!=='image'&&!imagePattern.test(x.id))).map(x=>x.id);if(n.type==='image'&&!list.length)list=all.filter(x=>imagePattern.test(x.id)).map(x=>x.id);if(!list.length)throw Error('接口成功，但没有返回适合当前节点的模型');n.models=list;n.model=n.type==='image'&&list.includes('Kwai-Kolors/Kolors')?'Kwai-Kolors/Kolors':list[0];n.endpoint=apiEndpoint(n);sessionStorage.setItem('key_'+n.provider,key);sessionStorage.setItem('models_'+n.provider+'_'+n.type,JSON.stringify(list));renderInspector();$('#output').textContent=`连接成功：当前节点已加载 ${list.length} 个可用模型。`;save();toast(`已加载 ${list.length} 个模型`)}catch(e){n.output=`模型读取失败\n原因：${e.message}\n建议：确认 Key 有效、账户有余额且网络可访问硅基流动。`;n.status='失败';$('#output').textContent=n.output;$('#output').classList.add('error-box');toast('读取失败，右侧已显示原因')}}
async function runNode(n){if(!n)return;if(n.type==='txt'){n.output=n.prompt;n.status='完成';save();render();return toast('TXT 文本已传递')}const key=sessionStorage.getItem('key_'+n.provider);if(!key){n.status='失败';n.output='生成失败\n原因：没有读取到 API Key。\n处理：在右侧填入 Key，再点“测试连接”。';save();render();return toast('缺少 API Key')}n.status='运行中';n.output='正在请求 '+(providers[n.provider]?.name||n.provider)+'…';save();render();const isImage=n.type==='image',controller=new AbortController(),timer=setTimeout(()=>controller.abort(),isImage?180000:60000),started=Date.now();try{const upstream=state.links.filter(l=>l.to===n.id).map(l=>state.nodes.find(x=>x.id===l.from)?.output).filter(x=>x&&!x.startsWith('http')).join('\n'),input=n.prompt||upstream||state.project.idea;if(!input)throw Error('没有图片提示词。请在节点、上游 TXT 节点或左侧核心创意中至少填写一处。');const endpoint=isImage?apiEndpoint(n):n.endpoint,body=isImage?{model:n.model,prompt:input,negative_prompt:n.negativePrompt||'模糊，低清晰度，水印，文字，畸形',image_size:n.imageSize||'1024x1024',batch_size:1,num_inference_steps:20,guidance_scale:7.5}:{model:n.model,messages:[{role:'system',content:n.prompt||'按用户要求完成任务'},{role:'user',content:upstream||state.project.idea||'请开始'}]};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},signal:controller.signal,body:JSON.stringify(body)}),trace=r.headers.get('x-siliconcloud-trace-id')||'',text=await r.text();let d;try{d=JSON.parse(text)}catch{d={message:text}}if(!r.ok){const reason=d.error?.message||d.message||d.code||text||'平台没有返回错误说明';throw Error(`HTTP ${r.status}：${reason}${trace?`\n追踪号：${trace}`:''}`)}if(isImage){const url=d.images?.[0]?.url||d.data?.[0]?.url;if(!url)throw Error('平台返回成功，但响应中没有图片地址。');n.output=url;n.imageMeta=`耗时 ${Math.round((Date.now()-started)/1000)} 秒${d.seed!==undefined?` · Seed ${d.seed}`:''}`;state.assets.push({id:Date.now(),name:`${seqText(n)}-${n.title}`,image:url})}else n.output=d.choices?.[0]?.message?.content||JSON.stringify(d,null,2);n.status='完成';toast(isImage?'图片生成成功':'节点运行成功')}catch(e){const timeout=e.name==='AbortError';n.output=`生成失败\n原因：${timeout?'请求超过等待时间，平台未及时返回':e.message}\n节点：${seqText(n)} ${n.title}\n模型：${n.model}\n建议：${timeout?'稍后重试或更换快速模型':'检查模型是否支持当前任务、Key 余额和参数设置。'}`;n.status='失败';toast('生成失败，右侧已显示原因')}finally{clearTimeout(timer)}save();render();renderAssets()}
function renderTasks(){$('#taskList').innerHTML=state.nodes.map(n=>`<div class="task"><span>${esc(n.title)}</span><i>${esc(n.status)}</i></div>`).join('')||'<small>暂无任务</small>'}
function showTab(name){['project','assets','tasks'].forEach(x=>$('#'+x+'Panel').hidden=x!==name);$$('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===name))}
function renderAssets(){$('#assetList').innerHTML=state.assets.map(a=>`<div class="asset"><img src="${a.image}"><span>${esc(a.name)}</span></div>`).join('')||'<small>暂无角色参考图</small>'}
$('#nodeCatalog').innerHTML=types.map(t=>`<button class="catalog" data-type="${t[0]}"><strong>${t[1]}</strong><small>${t[2]}</small></button>`).join('');$$('.catalog').forEach(b=>b.onclick=()=>addNode(b.dataset.type));$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('#addNode').onclick=()=>{state.pendingDrop=null;$('#nodeDialogTitle').textContent='添加节点';$('#nodeDialogHint').textContent='选择要添加的节点类型';$('#nodeDialog').showModal()};$('#cancelNode').onclick=()=>{state.pendingDrop=null;state.connecting=null;draw();$('#nodeDialog').close()};$('#deleteNode').onclick=()=>{if(!state.selected)return;state.nodes=state.nodes.filter(n=>n.id!==state.selected);state.links=state.links.filter(l=>l.from!==state.selected&&l.to!==state.selected);state.selected=null;save();render()};$('#clearCanvas').onclick=()=>{if(confirm('确定清空全部节点和连线？')){state.nodes=[];state.links=[];state.selected=null;save();render()}};
$('#provider').onchange=()=>{const n=state.nodes.find(x=>x.id===state.selected);n.provider=$('#provider').value;n.endpoint=apiEndpoint(n);n.model=n.type==='image'&&n.provider==='silicon'?'Kwai-Kolors/Kolors':providers[n.provider].models[0];renderInspector();save()};['nodeName','model','endpoint','apiKey','prompt','imageSize','negativePrompt'].forEach(id=>$('#'+id).onchange=sync);$('#prompt').oninput=()=>{const n=state.nodes.find(x=>x.id===state.selected);if(n){n.prompt=$('#prompt').value;save()}};$('#negativePrompt').oninput=()=>{const n=state.nodes.find(x=>x.id===state.selected);if(n){n.negativePrompt=$('#negativePrompt').value;save()}};$('#apiKey').oninput=()=>{const n=state.nodes.find(x=>x.id===state.selected);if(n)sessionStorage.setItem('key_'+n.provider,$('#apiKey').value)};$('#loadModels').onclick=loadModels;$('#testApi').onclick=loadModels;$('#runNode').onclick=()=>runNode(state.nodes.find(x=>x.id===state.selected));$('#runAll').onclick=async()=>{for(const n of state.nodes)await runNode(n)};
$('#zoomIn').onclick=()=>{state.zoom=Math.min(1.4,state.zoom+.1);render()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(.5,state.zoom-.1);render()};wrap.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.5,Math.min(1.4,state.zoom+(e.deltaY<0?.08:-.08)));render();save()};
let pan;wrap.onpointerdown=e=>{if(e.target.closest?.('.node')||e.target.closest?.('.toolbar'))return;pan={x:e.clientX,y:e.clientY,l:wrap.scrollLeft,t:wrap.scrollTop};wrap.setPointerCapture(e.pointerId)};wrap.onpointermove=e=>{if(pan){wrap.scrollLeft=pan.l-(e.clientX-pan.x);wrap.scrollTop=pan.t-(e.clientY-pan.y)}};wrap.onpointerup=()=>pan=null;wrap.ondblclick=e=>{if(e.target.closest?.('.node'))return;const r=wrap.getBoundingClientRect();state.pendingDrop={x:(e.clientX-r.left+wrap.scrollLeft)/state.zoom-30,y:(e.clientY-r.top+wrap.scrollTop)/state.zoom-35};$('#nodeDialogTitle').textContent='在这里添加节点';$('#nodeDialogHint').textContent='选择节点类型后，将在双击位置创建';$('#nodeDialog').showModal()};
['projectName','idea','episodes','duration','projectType','ratio','visualStyle'].forEach(id=>$('#'+id).oninput=save);$('#settings').onclick=()=>{renderApiList();$('#apiDialog').showModal()};function renderApiList(){$('#apiList').innerHTML=Object.entries(providers).map(([k,p])=>`<label class="api-row"><span>${p.name}</span><input type="password" data-key="${k}" value="${esc(sessionStorage.getItem('key_'+k)||'')}" placeholder="API Key"></label>`).join('');$$('[data-key]').forEach(e=>e.onchange=()=>sessionStorage.setItem('key_'+e.dataset.key,e.value))}
$('#addAsset').onclick=()=>$('#assetFile').click();$('#assetFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{state.assets.push({id:Date.now(),name:f.name,image:r.result});save();renderAssets()};r.readAsDataURL(f)};
$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='成成的工作台项目.json';a.click()};$('#import').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=async e=>{try{state=JSON.parse(await e.target.files[0].text());save();render();renderAssets()}catch{toast('项目文件无效')}};
$('#projectName').value=state.project.name;$('#idea').value=state.project.idea;$('#episodes').value=state.project.episodes;$('#duration').value=state.project.duration;$('#projectType').value=state.project.type||'短剧';$('#ratio').value=state.project.ratio||'16:9 横屏';$('#visualStyle').value=state.project.visualStyle||'';render();renderAssets();showTab('project');
